apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  labels:
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-desert21
          image: mongo:6.0.1
          ports:
          - containerPort: 27017
          volumeMounts:
          - mountPath: "/data"
            name: mongo-db-volume
      volumes:
        - name: mongo-db-volume
          persistentVolumeClaim:
            claimName: csi-pvc-main-data-storage-0