apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: main-data-storage
spec:
  selector:
    matchLabels:
      app: mypod
  serviceName: "desert-21-volume-claims"
  replicas: 1
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: desert-21-volume-claims
        image: busybox
        args:
          - sleep
          - infinity
        volumeMounts:
        - mountPath: "/data"
          name: csi-pvc
  volumeClaimTemplates:
  - metadata:
      name: csi-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: do-block-storage
